services:
  teradata-mcp-server:
    build:
      context: .
      args:
        - ENABLE_FS_MODULE=${ENABLE_FS_MODULE:-false}
        - ENABLE_EVS_MODULE=${ENABLE_EVS_MODULE:-false}
    image: teradata-mcp-server:latest
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - LOGMECH=TD2
      - MCP_TRANSPORT=streamable-http
      - MCP_PATH=/mcp/
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8001
      - PROFILE=${PROFILE}
    ports:
      - "${PORT:-8001}:8001"

  teradata-rest-server:
    build:
      context: .
      args:
        - ENABLE_FS_MODULE=${ENABLE_FS_MODULE:-false}
        - ENABLE_EVS_MODULE=${ENABLE_EVS_MODULE:-false}
    image: teradata-mcp-server:latest
    entrypoint: sh -c 'export MCP_TRANSPORT=streamable-http && mcpo --port 8002 --api-key "$MCPO_API_KEY" -- uv run teradata-mcp-server'
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - LOGMECH=TD2
      - MCP_TRANSPORT=streamable-http
      - MCP_PATH=/mcp/
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8001
      - PROFILE=${PROFILE}
      - MCPO_API_KEY
    ports:
      - "8002:8002"
    profiles: ["rest"]
